### ISSUE TITLE
New features and suggestion

### ISSUE THREAD

**Issue by FoxWorn3365** [AIPTU/PlayerWarn#2]
Hello, these are (in my opinion) features that will make this plugin kinda perfect:
- Can warn an offline player with the `/warn` command
- When a player is offline warned when he enter a notice will be shown.

And here some suggestions:
- You can easily do the expires thing by putting the UNIX expiration time in the warn data and when the command who shows the warn list or when a player join you can check if the current UNIX time is bigger than the expiration time and then remove the warn.
- When an offline warn is expired the user when joun the server is notified of this
- Discord webhooks are super easy to add: they're only an HTTP POST request and you can use discohook to generate the JSON

-Fox

**Comment by AIPTU** [comment]
Release in version: https://github.com/AIPTU/PlayerWarn/commit/d95f0f5ad0b0a97d9c02d8505226e747c380f8d6
